In [1]:
!git --version

git version 2.55.0.windows.3

In [2]:
%cd NDTA63

C:\Users\Admin\NDTA63

In [3]:
!git remote -v

origin	https://github.com/iammelvink/NDTA63.git (fetch)
origin	https://github.com/iammelvink/NDTA63.git (push)

In [5]:
!git remote set-url origin https://github.com/kgomotsego2001-droid/NDTA63.git

In [6]:
!git remote -v

origin	https://github.com/kgomotsego2001-droid/NDTA63.git (fetch)
origin	https://github.com/kgomotsego2001-droid/NDTA63.git (push)

 NDTA631 Data Analysis and Visualization


Project Title

Exploring the Relationship Between Employment and Freedom in South Africa

Datasets

Dataset 1: WB_AFS (Labour Force Statistics)

Dataset 2: FH_FIW (Freedom in the World)




The objective of this project is to investigate whether changes in South Africa's
political and civil freedom are associated with changes in labour-force
participation and employment.

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

%matplotlib inline

plt.style.use("ggplot")

In [8]:
import pandas as pd

employment = pd.read_csv(r"C:\Users\Admin\Downloads\WB_AFS.csv")
freedom = pd.read_csv(r"C:\Users\Admin\Downloads\FH_FIW.csv", low_memory=False)

print("Employment Dataset:", employment.shape)
print("Freedom Dataset:", freedom.shape)

Employment Dataset: (4287, 41)
Freedom Dataset: (109920, 41)

In [9]:
employment.head()

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,...,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3_LABEL,AGG_METHOD_LABEL,UNIT_TYPE_LABEL,DECIMALS_LABEL,DATABASE_ID_LABEL,TIME_FORMAT_LABEL,UNIT_MULT_LABEL,OBS_STATUS_LABEL,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,KGZ,AG_SH_OFFFR,_Z,_Z,_Z,PT,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,Employment in Agrifood System (AFS),CCYY,Units,Normal value,Public
1,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,KGZ,AG_SH_OFFFR,_Z,_Z,_Z,PT,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,Employment in Agrifood System (AFS),CCYY,Units,Normal value,Public
2,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,KGZ,AG_SH_OFFFR,_Z,_Z,_Z,PT,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,Employment in Agrifood System (AFS),CCYY,Units,Normal value,Public
3,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,KGZ,AG_SH_OFFFR,_Z,_Z,_Z,PT,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,Employment in Agrifood System (AFS),CCYY,Units,Normal value,Public
4,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,KGZ,AG_SH_OFFFR,_Z,_Z,_Z,PT,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,Employment in Agrifood System (AFS),CCYY,Units,Normal value,Public

In [10]:
freedom.head()

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,...,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3_LABEL,AGG_METHOD_LABEL,UNIT_TYPE_LABEL,DECIMALS_LABEL,DATABASE_ID_LABEL,TIME_FORMAT_LABEL,UNIT_MULT_LABEL,OBS_STATUS_LABEL,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,MDA,FH_FIW_F3,_Z,_Z,_Z,0_TO_4,...,Not Applicable,Not Applicable,Not Applicable,Number (real number),Zero,Freedom in the World,CCYY,Units,Normal value,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,MCO,FH_FIW_F3,_Z,_Z,_Z,0_TO_4,...,Not Applicable,Not Applicable,Not Applicable,Number (real number),Zero,Freedom in the World,CCYY,Units,Normal value,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,MNG,FH_FIW_F3,_Z,_Z,_Z,0_TO_4,...,Not Applicable,Not Applicable,Not Applicable,Number (real number),Zero,Freedom in the World,CCYY,Units,Normal value,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,MNE,FH_FIW_F3,_Z,_Z,_Z,0_TO_4,...,Not Applicable,Not Applicable,Not Applicable,Number (real number),Zero,Freedom in the World,CCYY,Units,Normal value,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,MAR,FH_FIW_F3,_Z,_Z,_Z,0_TO_4,...,Not Applicable,Not Applicable,Not Applicable,Number (real number),Zero,Freedom in the World,CCYY,Units,Normal value,Public

In [11]:
employment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4287 entries, 0 to 4286
Data columns (total 41 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   STRUCTURE               4287 non-null   object
 1   STRUCTURE_ID            4287 non-null   object
 2   ACTION                  4287 non-null   object
 3   FREQ                    4287 non-null   object
 4   REF_AREA                4287 non-null   object
 5   INDICATOR               4287 non-null   object
 6   SEX                     4287 non-null   object
 7   AGE                     4287 non-null   object
 8   URBANISATION            4287 non-null   object
 9   UNIT_MEASURE            4287 non-null   object
 10  COMP_BREAKDOWN_1        4287 non-null   object
 11  COMP_BREAKDOWN_2        4287 non-null   object
 12  COMP_BREAKDOWN_3        4287 non-null   object
 13  TIME_PERIOD             4287 non-null   int64
 14  OBS_VALUE               4213 non-null   float64
 15  AGG_METHOD              4287 non-null   object
 16  UNIT_TYPE               4287 non-null   object
 17  DECIMALS                4287 non-null   int64
 18  DATABASE_ID             4287 non-null   object
 19  TIME_FORMAT             4287 non-null   int64
 20  UNIT_MULT               4287 non-null   int64
 21  OBS_STATUS              4287 non-null   object
 22  OBS_CONF                4287 non-null   object
 23  FREQ_LABEL              4287 non-null   object
 24  REF_AREA_LABEL          4287 non-null   object
 25  INDICATOR_LABEL         4287 non-null   object
 26  SEX_LABEL               4287 non-null   object
 27  AGE_LABEL               4287 non-null   object
 28  URBANISATION_LABEL      4287 non-null   object
 29  UNIT_MEASURE_LABEL      4287 non-null   object
 30  COMP_BREAKDOWN_1_LABEL  4287 non-null   object
 31  COMP_BREAKDOWN_2_LABEL  4287 non-null   object
 32  COMP_BREAKDOWN_3_LABEL  4287 non-null   object
 33  AGG_METHOD_LABEL        4287 non-null   object
 34  UNIT_TYPE_LABEL         4287 non-null   object
 35  DECIMALS_LABEL          4287 non-null   object
 36  DATABASE_ID_LABEL       4287 non-null   object
 37  TIME_FORMAT_LABEL       4287 non-null   object
 38  UNIT_MULT_LABEL         4287 non-null   object
 39  OBS_STATUS_LABEL        4287 non-null   object
 40  OBS_CONF_LABEL          4287 non-null   object
dtypes: float64(1), int64(4), object(36)
memory usage: 1.3+ MB

In [12]:
freedom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109920 entries, 0 to 109919
Data columns (total 41 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   STRUCTURE               109920 non-null  object
 1   STRUCTURE_ID            109920 non-null  object
 2   ACTION                  109920 non-null  object
 3   FREQ                    109920 non-null  object
 4   REF_AREA                109920 non-null  object
 5   INDICATOR               109920 non-null  object
 6   SEX                     109920 non-null  object
 7   AGE                     109920 non-null  object
 8   URBANISATION            109920 non-null  object
 9   UNIT_MEASURE            109920 non-null  object
 10  COMP_BREAKDOWN_1        109920 non-null  object
 11  COMP_BREAKDOWN_2        109920 non-null  object
 12  COMP_BREAKDOWN_3        109920 non-null  object
 13  TIME_PERIOD             109920 non-null  int64
 14  OBS_VALUE               108156 non-null  object
 15  AGG_METHOD              109920 non-null  object
 16  UNIT_TYPE               109920 non-null  object
 17  DECIMALS                109920 non-null  int64
 18  DATABASE_ID             109920 non-null  object
 19  TIME_FORMAT             109920 non-null  int64
 20  UNIT_MULT               109920 non-null  int64
 21  OBS_STATUS              109920 non-null  object
 22  OBS_CONF                109920 non-null  object
 23  FREQ_LABEL              109920 non-null  object
 24  REF_AREA_LABEL          109920 non-null  object
 25  INDICATOR_LABEL         109920 non-null  object
 26  SEX_LABEL               109920 non-null  object
 27  AGE_LABEL               109920 non-null  object
 28  URBANISATION_LABEL      109920 non-null  object
 29  UNIT_MEASURE_LABEL      109920 non-null  object
 30  COMP_BREAKDOWN_1_LABEL  109920 non-null  object
 31  COMP_BREAKDOWN_2_LABEL  109920 non-null  object
 32  COMP_BREAKDOWN_3_LABEL  109920 non-null  object
 33  AGG_METHOD_LABEL        109920 non-null  object
 34  UNIT_TYPE_LABEL         109920 non-null  object
 35  DECIMALS_LABEL          109920 non-null  object
 36  DATABASE_ID_LABEL       109920 non-null  object
 37  TIME_FORMAT_LABEL       109920 non-null  object
 38  UNIT_MULT_LABEL         109920 non-null  object
 39  OBS_STATUS_LABEL        109920 non-null  object
 40  OBS_CONF_LABEL          109920 non-null  object
dtypes: int64(4), object(37)
memory usage: 34.4+ MB

In [13]:
employment.isnull().sum()

STRUCTURE                  0
STRUCTURE_ID               0
ACTION                     0
FREQ                       0
REF_AREA                   0
INDICATOR                  0
SEX                        0
AGE                        0
URBANISATION               0
UNIT_MEASURE               0
COMP_BREAKDOWN_1           0
COMP_BREAKDOWN_2           0
COMP_BREAKDOWN_3           0
TIME_PERIOD                0
OBS_VALUE                 74
AGG_METHOD                 0
UNIT_TYPE                  0
DECIMALS                   0
DATABASE_ID                0
TIME_FORMAT                0
UNIT_MULT                  0
OBS_STATUS                 0
OBS_CONF                   0
FREQ_LABEL                 0
REF_AREA_LABEL             0
INDICATOR_LABEL            0
SEX_LABEL                  0
AGE_LABEL                  0
URBANISATION_LABEL         0
UNIT_MEASURE_LABEL         0
COMP_BREAKDOWN_1_LABEL     0
COMP_BREAKDOWN_2_LABEL     0
COMP_BREAKDOWN_3_LABEL     0
AGG_METHOD_LABEL           0
UNIT_TYPE_LABEL            0
DECIMALS_LABEL             0
DATABASE_ID_LABEL          0
TIME_FORMAT_LABEL          0
UNIT_MULT_LABEL            0
OBS_STATUS_LABEL           0
OBS_CONF_LABEL             0
dtype: int64

In [14]:
freedom.isnull().sum()

STRUCTURE                    0
STRUCTURE_ID                 0
ACTION                       0
FREQ                         0
REF_AREA                     0
INDICATOR                    0
SEX                          0
AGE                          0
URBANISATION                 0
UNIT_MEASURE                 0
COMP_BREAKDOWN_1             0
COMP_BREAKDOWN_2             0
COMP_BREAKDOWN_3             0
TIME_PERIOD                  0
OBS_VALUE                 1764
AGG_METHOD                   0
UNIT_TYPE                    0
DECIMALS                     0
DATABASE_ID                  0
TIME_FORMAT                  0
UNIT_MULT                    0
OBS_STATUS                   0
OBS_CONF                     0
FREQ_LABEL                   0
REF_AREA_LABEL               0
INDICATOR_LABEL              0
SEX_LABEL                    0
AGE_LABEL                    0
URBANISATION_LABEL           0
UNIT_MEASURE_LABEL           0
COMP_BREAKDOWN_1_LABEL       0
COMP_BREAKDOWN_2_LABEL       0
COMP_BREAKDOWN_3_LABEL       0
AGG_METHOD_LABEL             0
UNIT_TYPE_LABEL              0
DECIMALS_LABEL               0
DATABASE_ID_LABEL            0
TIME_FORMAT_LABEL            0
UNIT_MULT_LABEL              0
OBS_STATUS_LABEL             0
OBS_CONF_LABEL               0
dtype: int64

In [15]:
employment = employment.dropna(subset=["OBS_VALUE"])

freedom["OBS_VALUE"] = pd.to_numeric(
    freedom["OBS_VALUE"],
    errors="coerce"
)

freedom = freedom.dropna(subset=["OBS_VALUE"])

In [16]:
print("Employment duplicates:",
      employment.duplicated().sum())

print("Freedom duplicates:",
      freedom.duplicated().sum())

Employment duplicates: 0
Freedom duplicates: 0

In [17]:
employment.describe()

       TIME_PERIOD    OBS_VALUE  DECIMALS  TIME_FORMAT  UNIT_MULT
count  4213.000000  4213.000000    4213.0       4213.0     4213.0
mean   2012.071208    11.473885       2.0        602.0        0.0
std       7.199086     3.797983       0.0          0.0        0.0
min    2000.000000     2.175569       2.0        602.0        0.0
25%    2006.000000     9.255308       2.0        602.0        0.0
50%    2012.000000    11.439263       2.0        602.0        0.0
75%    2018.000000    13.590404       2.0        602.0        0.0
max    2024.000000    41.323517       2.0        602.0        0.0

In [18]:
freedom.describe()

         TIME_PERIOD      OBS_VALUE  DECIMALS  TIME_FORMAT  UNIT_MULT
count  105408.000000  105408.000000  105408.0     105408.0   105408.0
mean     2019.450763       6.354546       0.0        602.0        0.0
std         4.039593      12.530845       0.0          0.0        0.0
min      2013.000000      -4.000000       0.0        602.0        0.0
25%      2016.000000       1.000000       0.0        602.0        0.0
50%      2019.000000       3.000000       0.0        602.0        0.0
75%      2023.000000       4.000000       0.0        602.0        0.0
max      2026.000000     100.000000       0.0        602.0        0.0

In [19]:
print("Employment Shape")
print(employment.shape)

print()

print("Freedom Shape")
print(freedom.shape)

Employment Shape
The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.
(4213, 41)

Freedom Shape
(105408, 41)

Question 1 Conclusion

The datasets were successfully imported into Python.

Several data preparation techniques were performed:

- Missing values were identified.
- Missing numerical observations were removed.
- Duplicate records were checked.
- Numerical variables were converted to the correct data types.
- Descriptive statistics were generated.

After cleaning, both datasets were ready for numerical analysis,
visualisation and database integration.